export const GET_BOOKS_LIST = "GET_BOOKS_LIST";
export const UPDATE_BOOKS_LIST ="UPDATE_BOOKS_LIST";

export const GET_WISH_LIST = "GET_WISH_LIST";
export const ADD_BOOK_TO_WL = "ADD_BOOK_TO_WL";
export const DELETE_BOOK_WL = "DELETE_BOOK_WL";